baseURL = 'http://maxcroasdale.github.io/'
languageCode = 'en-us'
title = 'Welcome to Little Sparta'
theme = 'hugo-liftoff'


[menu]
[[menu.main]]
identifier = 'Before and after'
name = 'Before and after'
title = 'Before and after'
url = '/Before/'
weight = 2

[[menu.main]]
identifier = 'Blog'
name = 'What we do at the weekend'
title = 'What we do at the weekend'
url = '/posts/'
weight = 1
